name: bizconnect_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-318.0.dev

dependencies:
  global_configuration: ^2.0.0
  qr_code_scanner: ^1.0.1
  flutter:
    sdk: flutter
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
